events {}

http {
  upstream active_wordpress {
    server wordpress-new:80;
    # To simulate DNS before cutover, change the line above to:
    # server wordpress:80;
    # To simulate DNS after cutover, use:
    # server wordpress-new:80;
  }

  server {
    listen 80;
    server_name practice.localhost;

    location / {
      proxy_pass http://active_wordpress;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
